"""Initial migration with enhanced Fund model

Revision ID: 282e138cc91b
Revises: 
Create Date: 2025-10-24 19:10:51.945197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282e138cc91b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_funds')
    with op.batch_alter_table('funds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('recurring_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('next_deposit_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('skip_next', sa.Boolean(), nullable=True))
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('fund_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('bill_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('transaction_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('is_autopay', sa.Boolean(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('fund_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'bills', ['bill_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('fund_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('is_autopay')
        batch_op.drop_column('transaction_type')
        batch_op.drop_column('bill_id')
        batch_op.drop_column('category')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('funds', schema=None) as batch_op:
        batch_op.alter_column('fund_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('balance',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
        batch_op.drop_column('skip_next')
        batch_op.drop_column('next_deposit_date')
        batch_op.drop_column('recurring_amount')
        batch_op.drop_column('goal')

    op.create_table('_alembic_tmp_funds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('fund_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('balance', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('goal', sa.FLOAT(), nullable=True),
    sa.Column('recurring_amount', sa.FLOAT(), nullable=True),
    sa.Column('next_deposit_date', sa.DATE(), nullable=True),
    sa.Column('skip_next', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
